### ISSUE TITLE
assign existing workspaces to subjects?

### ISSUE THREAD

**Issue by rdiaz02** [akirak/frame-workflow#8]
Thanks for frame-workflow!
I cannot find a way to assign existing workspaces to subjects. With `frame-workflow-make-frame` and `frame-workflow-switch-frame` I can create new ones but I would like to assign existing ones to new names (similar to Xmonad's idea of renaming workspaces or `exwm-nw-set` in https://github.com/pjones/exwm-nw). Is this possible?

**Comment by akirak** [comment]
It is basically possible but comes with some limitation. Especially, `:make-frame` option of the new subject will not apply to such a frame. If you use integration with frame-purpose, existing frames won't have the purposes of the new subjects. If it is what you want, I will add the feature you requested.

To address this issue, I added a command to *replace* an existing frame --- create a new frame with a subject and deletes the original frame. It is available as `frame-workflow-replace-frame` in recent commits. This is not a perfect solution, though. The layout of the original frame is not retained, and the window configuration history of the original frame is lost.

**Comment by rdiaz02** [comment]
Thanks a lot! 
Please, no, do not write the code just for me. I now see that using `frame-workflow-replace-frame` should fit my needs, since losing the layout and configuration is not a big problem; I basically wanted this to be able to assign names to workspaces, instead of just using numbers, and sometimes I realize that I want to name it after the workspace is already created and populated by frames and X windows. Thanks again.
